### ISSUE TITLE
Gnome-shell crash on screen unlock

### ISSUE THREAD

**Issue by podcherklife** [zagortenay333/cronomix#104]
Running Ubuntu 19.04

This is basically the same issues as https://github.com/zagortenay333/timepp__gnome/issues/24

Sometimes when unlocking screen gnome-shell crashes. 

Here is the relevant log entry:

```
gnome-shell[13379]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
gnome-shell[13379]: JS ERROR: Error: Argument 'file' (type interface) may not be null
                                              loadTheme@resource:///org/gnome/shell/ui/main.js	:357:13
                                              _load_stylesheet@/home/myuser/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:575:13
```
Here, `loadTheme@resource:///org/gnome/shell/ui/main.js:357:13` refers to this line: https://github.com/GNOME/gnome-shell/blob/8864816b94205c52037f9258123ec6c3d4cd38c1/js/ui/main.js#L365

I can also reproduce this by repeatedly enabling/disabling extension in tweak-tool. Shell crashes after a couple of dozens of clicks on toggle.

**Comment by podcherklife** [comment]
Also I've noticed that crash probability depends on the amount of stuff on the screen. On a new session it takes about ten or more lock/unlock operations to get crash. If I've got several workspaces filled with windows, crash probability rises to about 50%.
I would assume that the crash happens due to some kind of race condition in Mainloop.idle_add callback, but I have no idea how gnome internals work, so this assumption may be completely wrong.

**Comment by lockejan** [comment]
I've noticed the same on fedora 30 and latest gnome. I'm using the repo version of the extension not the one from gnome-extensions-website.
Already opened an [Issue](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1349) on the gnome project.
After disabling the extension the shell crashes seem gone, but I'm still investigating.
Just pulled the latest version from this repo.

**Comment by michaldaniel** [comment]
So this is the issue I've been hunting for the past month.

**Comment by zagortenay333** [comment]
Well, it seems the issue is that during unlock time we fail to get the stylesheet file path. That is, here: https://github.com/zagortenay333/timepp__gnome/blob/9db119bd4cce844774e9f137c01e0ac546b556f8/extension.js#L552-L571 we end up with `this.custom_stylesheet` being null and the call to `load_stylesheet` followed by `loadTheme` leads to a hard crash...

Perhaps replacing this: https://github.com/zagortenay333/timepp__gnome/blob/9db119bd4cce844774e9f137c01e0ac546b556f8/extension.js#L546

with:
```js
Mainloop.idle_add(() => this._load_stylesheet());
```

Anyway, we can test this maybe by adding a little conditional here: https://github.com/zagortenay333/timepp__gnome/blob/9db119bd4cce844774e9f137c01e0ac546b556f8/extension.js#L571-L575

like this:
```js
if (this.custom_stylesheet) {
    St.ThemeContext.get_for_stage(global.stage).get_theme().load_stylesheet(this.custom_stylesheet);

    // reload theme
    Main.reloadThemeResource();
    Main.loadTheme();
}
```
and seeing if the crash still hapens.

Somebody else will have to do it though; I'm not on gnome-shell.

**Comment by mogorman** [comment]
I applied the patch you described and tried locking and unlocking screen, it still crashes.

**Comment by ben-mathu** [comment]
Hi,
I am posting this here because I think it might be related. So this crash happens 100% of the time on my machine: Ubuntu 19.10 and Gnome version 3.34.1.
To recreate the issue, run new pomo and let it run till the end of the long break.
I am not sure if this happen for everyone, but could the crash occur when the pomodoro tries to start a new tracker?

**Comment by thadeupenna** [comment]
The same configuration here: Ubuntu 19.10 and Gnome version 3.34.1. I do not use pomodoro, only alarm and todo.txt,  and I find the same issue as well.  Alt-F2 + r and it crashes. 
dez 24 11:04:56 helles gnome-shell[14679]: GNOME Shell crashed with signal 11
dez 24 11:04:56 helles gnome-shell[14679]: == Stack trace for context 0x5555cf71d320 ==
dez 24 11:04:56 helles gnome-shell[14679]: #0   5555d041b970 i   resource:///org/gnome/shell/ui/main.js:385 (7f43714d4040 @ 200
dez 24 11:04:56 helles gnome-shell[14679]: #1   5555d041b8c8 i   /home/tjpp/.local/share/gnome-shell/extensions/timepp@zagorten
dez 24 11:04:56 helles gnome-shell[14679]: #2   5555d041b850 i   /home/tjpp/.local/share/gnome-shell/extensions/timepp@z

**Comment by digitalethics** [comment]
> Somebody else will have to do it though; I'm not on gnome-shell.

What DE do you currently use?

**Comment by maxim317** [comment]
I madly liked this extension! It is especially convenient to work with a kanban board. Only this expansion can be a kanban board.
But I could not defeat the shell crash.
I used distributions from Github and from extensions.gnome.org. I applied the patch that is posted in this thread.
I do not know how to help myself.
Fedora 32, Gnome 3.36.2

**Comment by lfom** [comment]
It seems that theme loading is somewhat bugged now (or at least not as stable as it should). I was able to fix the annoying errors about deprecated functions in gnome-shell log, as well as the problem loading the custom style sheet with a small side effect: the top panel flashes when the extension is loaded (because it needs to reset the theme once it changes, otherwise a crash will follow, also crashing the whole shell on Wayland).I haven't used the extension before (I came here looking for a fix to a problem in another project) so I am not sure everything works as it should, but there is no more crashes or errors in the log. I am using Gnome Shell 3.36.4, but probably the changes will make it easier to make it compatible with 3.38 when it is released.
If there is demand I can send a PR.
Regards
