### ISSUE TITLE
[temps-dir and todos file] How do I change place for them ?

### ISSUE THREAD

**Issue by dxokal** [zagortenay333/cronomix#116]
Hey!

I'm really fond of time++ gnome extension. It let me focus on my work at a given time. Thanks for developping it.

When installing it, I choosed the default place for temps-dir and todos file which is my home dir. I tried to change this in vain. How do I do it ?

Regards

**Comment by zagortenay333** [comment]
temps-dir? You mean the directory where you put your csv files?

1. First move you csv folder where you want it.
2. Then go to the file settings in the popup menu and change the file paths.
![image](https://user-images.githubusercontent.com/11144630/63511096-884d5a80-c4e0-11e9-9a9f-7963070f0f3b.png)
3. I believe you'll have to delete the old csv folder again because time++ monitors it and will
make a new empty one each time you move it.

**Comment by dxokal** [comment]
It works ! Thank you.
