### ISSUE TITLE
gnome-shell killed by SIGTRAP

### ISSUE THREAD

**Issue by viktorov-aa** [zagortenay333/cronomix#126]
Gnome: gnome-shell-3.34.4-1.fc31
OS Release: Fedora release 31 (Thirty One)

When the extension is turned on, the gnome periodically crashes.
I have error - "gnome-shell killed by SIGTRAP" 
My logs in the attachment. 
Can I do something to diagnose?

PS
Sorry for my English =)
[userlog.txt](https://github.com/zagortenay333/timepp__gnome/files/4310774/userlog.txt)

**Comment by zagortenay333** [comment]
Mind trying the version from github again?

**Comment by kelltob** [comment]
I got the same crashes on Fedora 31 / Gnome Shell 3.34.4

When 'Resume tracking after abrupt restart' is deactivated gnome shell crashes but doesn't freeze.
After a few restarts/crashes of gnome shell the extension is getting deactivated by shell I think? (Icon is still in status bar but I'm not able to start tracking.)

Maybe this issue is a duplicate to #104 ? I got the same behavior as @podcherklife in https://github.com/zagortenay333/timepp__gnome/issues/104#issuecomment-505430147_ descriped.

How can I replace the installed version by the one from github?

**Comment by zagortenay333** [comment]
Are you people still on 3.34? Can you try 3.36. I'd love to just close this and not bother with 3.34 anymore.

**Comment by kelltob** [comment]
Not anymore. I'm on 3.38.1 but have not tested it yet.

**Comment by zagortenay333** [comment]
Alright closing then.
