### ISSUE TITLE
Time Tracker accuracy

### ISSUE THREAD

**Issue by Algram** [zagortenay333/cronomix#13]
Hello. How does the time tracker work when dealing with values below 1min:
When I start tracking for a task and stop the tracking after 45 seconds, does the tracker still count those 45 seconds?

Thank you!

**Comment by zagortenay333** [comment]
Eh, nope. I ignore anything below 1min since you will lose those seconds anyway when they get stored into the csv file (the csv file only holds hours and minutes).

So you could lose up to a minute per day, but I don't think it's a big deal. The reason I did it that way was to keep the csv file a little simpler.
So that's about 6 hours per year in the extreme case.

Is it something that bothers you? The issue with changing it is that there will be problems when parsing the an existing csv file...

**Comment by Algram** [comment]
You can lose more than 1 minute a day if you switch tasks rapidly.
For example I switch my task every time I change my workspace. For example I have Firefox on WS1 and my IDE on WS2. Now there is a good chance that I will just switch to WS1 to read up on something real quick and then switch back to WS2. That time would then be lost.

Maybe you could add an option with a conversion mechanism or you just display a message that the file is incompatible?

EDIT: Also I would only write to the file once a task timer is turned off. Otherwise you would have to update the file every second.

**Comment by zagortenay333** [comment]
No, you cannot lose more than 1 minute. The time is counted in seconds, and at the moment it is written to the csv file the current seconds are discarded. I am not appending to the daily csv file, I'm overwriting it whole.
The only way to lose more then a minute is if you restart the extension a lot of times.

But yeah, I should have stored the seconds into the csv file from the start. Will see; I should probably do it sooner than later...

**Comment by Algram** [comment]
Oh so that means seconds are actually counted? So if I start a Task, let it run for 45 seconds, stop it and then start it again for 15 seconds there will be 1 minute in the CSV? If that's the case there is no problem with keeping it as it is in my eyes.

**Comment by zagortenay333** [comment]
Yeah, that's how it works, but this way you could lose 6 hours per year in the extreme case.

**Comment by Algram** [comment]
What do you mean with "restarting the applet a lot of times"? Do you mean toggling the extension on and off or just starting and stopping timers? I have been running it for an hour now and it seems there is some time that gets lost, although I am not quite sure.

**Comment by zagortenay333** [comment]
I mean toggling the extension on or off, or restarting the system, etc.

**Comment by zagortenay333** [comment]
Actually I just realized why I did it this way.. It's because I don't want to have to write to the csv file every second.. So I'm updating the csv file every minute and as a result you may lose those seconds, so I figured I may as well leave out the seconds.

Then again, I can write to it every 60 sec as long as I write the seconds once the extension is disabled... 

Whatever. I don't think this is a big deal so I'm gonna leave it like this for now.
