### ISSUE TITLE
[Gnome 3.36] time tracker not hide finish task

### ISSUE THREAD

**Issue by rtsantanna** [zagortenay333/cronomix#136]
In Gnome Version 3.36.1, time tracker not filter or hide tasks finish.

**Comment by rtsantanna** [comment]
Is possible change parameter hide finish task in some files ? While checking for this bug?

**Comment by Sampathfrnd4ever** [comment]
Hi, I've just started to use Ubuntu 20.04.1, with Gnome version 3.36.3 and I'm new to linux and interested to learn. I'm trying to turn off and I'm not able to because it displays "Error" in the installed extension section. Even after uninstallation it is displayed in the top bar and lock screen too. please hep.

**Comment by zagortenay333** [comment]
Can you try the now updated 3.36 version and see if the bug is still there? The one from github that is.

**Comment by zagortenay333** [comment]
Oh wait. I misread this issue. I think you mean why does the stats view show finished tasks? That's the intended behaviour, not a bug :). There is no filtering feature in the stats view for this stuff and I don't intend to implement it.
