### ISSUE TITLE
Tracking stops seemingly randomly on Pop!_OS 20.10

### ISSUE THREAD

**Issue by rscircus** [zagortenay333/cronomix#149]
_Expected behavior:_

When I click the ▶️  button, a tasked is tracked until I press the :pause_button: button while the taskbar icon is recolored to something-is-going-on-color during this time.

_Actual behavior:_

When I click the ▶️  button, a tasked is tracked until a random moment in time, when it's not tracked anymore and the taskbar Icon recolored to it's default color.

OS:

- Pop!_OS 20.10 - vanilla installation (tested this on a VM, too).

**Comment by zagortenay333** [comment]
Honestly, abandon all hope. There's no debugging this; not gonna even try.

The time tracker is set up to stop tracking whenever the file it's tracking has been modified from someone outside. For example, if you write to the todo.txt, the tracker will stop. Or maybe if you have the file in dropbox folder, then dropbox might write to it

I think there is a feature in the settings called something like "continue tracking after restart" or something like that. Maybe it might help.

**Comment by rscircus** [comment]
Haha, that was an honest answer.

I think, you mean this option:

![](https://user-images.githubusercontent.com/1167114/103485724-b8a54880-4df8-11eb-8fee-89549c95096d.png)

Had it on already.

**Comment by rscircus** [comment]
Haha, that was an honest answer.

I think, you mean this option:

![](https://user-images.githubusercontent.com/1167114/103485724-b8a54880-4df8-11eb-8fee-89549c95096d.png)

Had it on already.

**Comment by rscircus** [comment]
This is the weirdest bug, I've ever seen on github. Copy and pasting the text from the [previous](https://github.com/zagortenay333/timepp__gnome/issues/149#issuecomment-753656679) comment results in the result above.

**Comment by Mascinissa** [comment]
I'm having the same issue on Arch Linux with Gnome 3.38.2. Precisely the issue is that, **sometimes**, the task tracking stops unexpectedly 30 seconds after pressing the ▶️ button.

Here is how to reproduce the issue:
1. Restart the gnome-session
2. Press ▶️ to start tracking any task. At this point, the tracking works properly.
3. Now lock the screen while the tracking is ON then unlock it back. Now the tracking stops and this is the expected behavior.
4. From now on when you press the ▶️ button, the tracking stops automatically after 30 seconds.

I took a quick look at the code and I understood that 30 seconds is the interval for saving the tracking progress. After digging a bit more I think that the problem comes from file monitors used in ` _write_daily_csv_file ()` 

https://github.com/zagortenay333/timepp__gnome/blob/767aa8cc7ec84a9d7fb2e552adfcc0c29a201cda/sections/todo/time_tracker.js#L231-L237

I didn't take the time to try to understand the exact origin of the bug, but I hope these details will help the maintainer fix it.

Thanks,

**Comment by zagortenay333** [comment]
I'ts always those damn file monitors; they have been causing endless headaches...

I don't know whether it's me misusing the API or whether there are bugs involved in the js bindings. Something about them just feels off. For example, you can't disable a file monitor, write to the file, and then enable the monitor. As soon as you enable it agaom the monitor fires off, even though js is single threaded.

**Comment by he7d3r** [comment]
The bug also happens on Ubuntu 20.10.

**Comment by zandao** [comment]
https://github.com/zagortenay333/timepp__gnome/blob/767aa8cc7ec84a9d7fb2e552adfcc0c29a201cda/sections/todo/time_tracker.js#L231-L237

Line 234 is throwing an exception after being called from _tracker_tic at line 352 after screen unlock.

https://github.com/zagortenay333/timepp__gnome/blob/767aa8cc7ec84a9d7fb2e552adfcc0c29a201cda/sections/todo/time_tracker.js#L348-L355

Maybe it has something to do with this [Gnome Shell issue](https://gitlab.gnome.org/GNOME/gjs/-/issues/297).
If it is the case, it is solved on Gnome 40, if not it is still a mystery.

**Comment by tomasfrtala** [comment]
I found that restarting gnome shell with `ALT+F2` and `r` before clicking on the play button, will not break recording after 30s. Ubuntu 20.04, gnome 3.36.8, X11

**Comment by zagortenay333** [comment]
Shouldn't be an issue in the new version of the extension.
