### ISSUE TITLE
Timer and stopwatch stop when screen is locked

### ISSUE THREAD

**Issue by anupam207** [zagortenay333/cronomix#5]
System: Ubuntu GNOME 17.04, GNOME shell version 3.24.2
- Start timer or stopwatch
- Lock the screen
- Unlock the screen to find timer/stopwatch has stopped

**Comment by zagortenay333** [comment]
Srry, can't be solved. All extensions get disabled when the lock screen gets turned on and there is no way for an extension to know whether it's being disabled because the lock screen is turning on or otherwise. :/

**Comment by zagortenay333** [comment]
There is already a bug open on this:
https://bugzilla.gnome.org/show_bug.cgi?id=781760

**Comment by alexwhitman** [comment]
Rather than running a timer in the background, why not store the Unix timestamp on start, then compare to "now" for display.

**Comment by zagortenay333** [comment]
I'm already using diffs in monotonic time.

The issue is that the timer, pomodoro and alarm need to be able to throw notifications or else they are useless. The stopwatch already keeps the elapsed time in a cache file so it persists session shutdowns, but I don't bother computing elapsed time for it since the other timers can't work like that.

**Comment by ghost** [comment]
@zagortenay333 I proposed a local solution here: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/75#issuecomment-331390300

In your case this is equivalent to not stop the background task in the lock screen, but you can hide the user interface or then like Florian say "Yes, but IMHO any extension that is caught gaming the system like that shouldn't pass review on extensions.gnome.org.", your extension will not pass the review.

I don't know what is doing your extension really, but is nice to me see that you wrote an extension.

**Comment by zagortenay333** [comment]
Hi, @lestcape :smile:

Yeah, I don't want to do this if it isn't explicitly supported by the gnome devs. I commented on this bug report too: https://bugzilla.gnome.org/show_bug.cgi?id=781760

From what I see, it would be trivial to make this an opt-in for extensions, so I hope they do it.

> I don't know what is doing your extension really, but is nice to me see that you wrote an extension.

It's got a readme. :laughing:
Yeah, it's a bit of a behemoth tbh. Probably one of (if not the) biggest shell extensions ever. More of an app really.

**Comment by ghost** [comment]
@zagortenay333 is not only the readme. What i say is i don't know what is doing your extension at the level of the code, to proposed a patch because is so big, but if you want to wait for an explicitly support that ok. :)

**Comment by FreddieChopin** [comment]
The same is true for time-tracking feature. Without persistency across screen saver and also shell restarts (these happen from time to time for various reasons) the time-tracking feature is not usable at all. Time-tracking should _never_ stop without explicit user action - I would say that it should even be persistent across full system restarts

Additionally I would suggest saving the start and end timestamp of tracked period in the CSV file instead of the time passed. Otherwise if you notice that your tracker is not running after some random time you have absolutely no idea how much should you add in the CSV file. All you can get from the CSV is that 47 minutes were tracked, but you don't remember at what time exactly you started the task (otherwise you wouldn't need a time-tracker, would you (; ).

To reproduce:

1. start tracking
2. restart the shell with Alt + F2, enter `r`, hit Enter
3. time-tracking is stopped

**Comment by zagortenay333** [comment]
@FreddieChopin 
Not sure how the tracker turning off after a system restart is making it _unusable_; it's pretty darn usable to me.
I too would forget sometimes to turn the tracker on, that's why I added that script which turns it on automatically when I am on a particular workspace.

Just as you can forget to turn it on, you could also easily forget to turn it off, so it doesn't seem like it would solve much if I automatically continue tracking after a system restart.

I could add work intervals for a particular day so one could to tell when they started the tracker last time and I guess it would be a neat statistic to have, but tbh it doesn't seem worth the effort. Plus, I would need to change the format of the csv files...

**Comment by FreddieChopin** [comment]
> Not sure how the tracker turning off after a system restart is making it unusable; it's pretty darn usable to me.

Don't get me wrong, your software is very nice and packed with nice features, but these minor issues are really making the time tracker unusable *for me*. If you only want to track stuff you do on your PC then fine, no need to deal with restarts, but why track things outside of the computer? I hope you would like the software to be usable to as many use-cases as possible, not only yours.

This really boils down to the problem of logging only the duration, not start/stop timestamps - if there's a power shortage or if your PC crashes or you quickly need to do a restart after some important software upgrade, the tracker stops, even though you did not ask it to.

> I could add work intervals for a particular day so one could to tell when they started the tracker last time and I guess it would be a neat statistic to have, but tbh it doesn't seem worth the effort. Plus, I would need to change the format of the csv files...

I'm sorry to hear that you don't consider this worthwhile... This is not about having a nice statistics - your tracker does stop when the screensaver starts or when GNOME shell crashes (unfortunately quite frequent behaviour of most recent GNOME, every day at least twice). The problem here is that it's easy to forget about turning it on back again - assuming that you actually know that it stopped (it's easy to miss the fact that GNOME shell crashed). If I'm working on a project which requires me to just think through some issue with a sheet of paper and a pen, it's a huge distraction if I have to remember to move my mouse every 4 minutes (to avoid screensaver)...

Just as you wrote, it is also easy to forget to turn the tracking off. True. That's why having a start and end time in the CSV file would make it _much_ easier to fix such issues. If all you see there is that "47 minutes" were tracked, you know nothing. However if you'd see that the activity started at 2:30 PM then you could probably remember more-or-less when you stopped it or you know that you are still doing it, so the "fix" of data is trivial - either enter the end hour or just delete it (marking the activity as "in progress").

For the record - Hamster Time Tracker (which we are still using but would very much like to switch) does allow all of this:
- tracking does not stop after shutdown (can be configured);
- tracking does not stop when GNOME shell crashes;
- tracking does not stop when screensaver starts (can be configured);
- activities are recorded with start/end timestamps, so it's easy to fix/edit/add/delete them;

**Comment by zagortenay333** [comment]
I added this to the todo for when I get the inspiration: 
![screenshot from 2018-02-27 18-32-04](https://user-images.githubusercontent.com/11144630/36745623-6a7a0b24-1bf0-11e8-95d5-8c3a23aa30a9.png)

**Comment by zagortenay333** [comment]
@FreddieChopin I added the time intervals thingy now. There is a switch in the settings for making the tracker automatically restart after an abrupt start (on by default). Let me know if it works well.

Also the stats view got some updates to show the intervals among other things :smile: 
![screenshot from 2018-03-09 19-13-36](https://user-images.githubusercontent.com/11144630/37222578-fb53e84c-23cd-11e8-8bad-20f2e6d448dd.png)

**Comment by FreddieChopin** [comment]
Great - thanks! I'll check it out soon!

**Comment by hedning** [comment]
Awesome, this really made it things much more usable for me. I'm developing a gnome extension of my own and restart gnome shell quite a lot, which would break the tracking.

Also loving the additions to the stats view :smile:

**Comment by zagortenay333** [comment]
ping @FreddieChopin
