### ISSUE TITLE
Notification sound doesn't work 

### ISSUE THREAD

**Issue by unit-cesar** [zagortenay333/cronomix#61]
I tested with: **Default sound(ogg)** and **MP3**

_Ubuntu 17.10
GNOME Shell 3.26.2_

Great App!!! And I'll be grateful for any help.

**Timer Screen**
![image](https://user-images.githubusercontent.com/11687314/38892239-15ec2db0-425d-11e8-8cf2-b9b5cbe1ee8d.png)

**Alarm Screen**
![image](https://user-images.githubusercontent.com/11687314/38892166-de962bea-425c-11e8-8c97-10fe2bec117a.png)

**Comment by zagortenay333** [comment]
Are you using the github version?

**Comment by unit-cesar** [comment]
No, I used GNOME Shell Extensions

https://extensions.gnome.org/extension/1238/time/

**Comment by zagortenay333** [comment]
That is very outdated unfortunately. Gonna close this since the github version doesn't have this issue.

**Comment by unit-cesar** [comment]
I followed your suggestion, downloaded the Github version, but I still do not hear anything.

**Comment by zagortenay333** [comment]
The notification plays but you can't hear any sound?

Type into a terminal:
```
journalctl /usr/bin/gnome-shell -f -o cat 
```
Then play a notification and see if the terminal spits any errors.

**Comment by unit-cesar** [comment]
No error! 
I tried the **default** notification and the **full screen**. No sound! No error in terminal with command above.

**Comment by zagortenay333** [comment]
Try changing the `Repeat notification sound?` in the default timer preset.

Try to see if there are any errors when executing: `journalctl /usr/bin/gnome-shell -r  | less` with regards to this extension.

**Comment by unit-cesar** [comment]
**Good news! It works.**
I heard the beep when checking repeat

![image](https://user-images.githubusercontent.com/11687314/38902949-15179e76-4279-11e8-8d57-328dee5f6052.png)

**Comment by unit-cesar** [comment]
But how do not be repetitive?

**Comment by zagortenay333** [comment]
So you hear the sound when repeat is checked but you can't hear it when you uncheck that?

**Comment by unit-cesar** [comment]
That's it!

**Comment by zagortenay333** [comment]
Is it fixed or what?

**Comment by unit-cesar** [comment]
My intention was to listen only once, without making use of the "Repeat notification sound". However, I can adapt, but I believe that the proposal is to be able to repeat or not, right?

For now you can consider fixed if you want!

**Thank you very much and congratulations for the excellent app.**

**Comment by zagortenay333** [comment]
This is a bug. You can uncheck that and it should play the sound only once; however, I cannot reproduce this. Unless you can use the above commands I gave to find an error I can't help you. 

Uncheck that repeat option, play a notification, and show me the output of `journalctl /usr/bin/gnome-shell -r` here.

**Comment by CesarDevesa** [comment]
**I tried 3 times the "TIMER" and once the "ALARM", did not register error at that time, the errors that appeared were previous to the tests. Anyway, follow the log...**

![image](https://user-images.githubusercontent.com/11687314/38929750-c6f89a54-42e3-11e8-88cd-678e4ed2e2db.png)
-- Logs begin at Sat 2018-03-24 08:36:59 -03, end at Wed 2018-04-18 08:36:08 -03. --
abr 18 08:19:20 pc-main org.gnome.Shell.desktop[3251]: [3740:3779:0418/081920.109113:ERROR:upload_data_presenter.cc(73)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::
abr 18 07:58:01 pc-main org.gnome.Shell.desktop[3251]: [1:16:0418/075801.964189:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:58:01 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/075801.680549:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:57:07 pc-main org.gnome.Shell.desktop[3251]: [3786:3786:0418/075707.193397:ERROR:gles2_cmd_decoder.cc(10094)] [.DisplayCompositor-0x30244d2e7c00]RENDER WARNING: texture bound to texture unit 2 is not r
abr 18 07:57:07 pc-main org.gnome.Shell.desktop[3251]: [3786:3786:0418/075707.193114:ERROR:gles2_cmd_decoder.cc(10094)] [.DisplayCompositor-0x30244d2e7c00]RENDER WARNING: texture bound to texture unit 1 is not r
abr 18 07:57:07 pc-main org.gnome.Shell.desktop[3251]: [3786:3786:0418/075707.192776:ERROR:gles2_cmd_decoder.cc(18268)] [.DisplayCompositor-0x30244d2e7c00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextu
abr 18 07:57:07 pc-main org.gnome.Shell.desktop[3251]: [3786:3786:0418/075707.191996:ERROR:gles2_cmd_decoder.cc(18268)] [.DisplayCompositor-0x30244d2e7c00]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextu
abr 18 07:55:11 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/075511.799952:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:55:05 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/075505.217934:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:54:46 pc-main org.gnome.Shell.desktop[3251]: [1:1:0418/075446.114039:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR PIPELINE_ERROR_DECODE
abr 18 07:54:46 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/075446.113870:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
abr 18 07:54:46 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/075446.113777:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"Failed to send video packet for decoding: EOS"}
abr 18 07:54:08 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/075408.266793:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:54:07 pc-main org.gnome.Shell.desktop[3251]: [1:1:0418/075407.838369:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
abr 18 07:54:07 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/075407.838164:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
abr 18 07:51:58 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/075158.213571:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:51:31 pc-main org.gnome.Shell.desktop[3251]: [1:1:0418/075131.773657:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
abr 18 07:51:31 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/075131.772315:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
abr 18 07:51:29 pc-main org.gnome.Shell.desktop[3251]: [1:1:0418/075129.609195:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
abr 18 07:51:29 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/075129.607305:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
abr 18 07:51:06 pc-main org.gnome.Shell.desktop[3251]: [1:1:0418/075106.973377:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
abr 18 07:51:06 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/075106.973069:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
abr 18 07:50:44 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/075044.439418:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:49:17 pc-main org.gnome.Shell.desktop[3251]: [1:1:0418/074917.414483:ERROR:render_media_log.cc(30)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_NO_SUPPORTED_STREAMS
abr 18 07:49:17 pc-main org.gnome.Shell.desktop[3251]: [1:19:0418/074917.414295:ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: no supported streams"}
abr 18 07:48:56 pc-main org.gnome.Shell.desktop[3251]: [1:17:0418/074856.806849:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:48:32 pc-main org.gnome.Shell.desktop[3251]: [1:18:0418/074832.928722:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
abr 18 07:21:21 pc-main org.gnome.Shell.desktop[3251]: [3740:3767:0418/072121.937768:ERROR:in_progress_cache_impl.cc(93)] Could not read download entries from file because there was a read failure.
abr 18 07:21:20 pc-main org.gnome.Shell.desktop[3251]: ATTENTION: default value of option force_s3tc_enable overridden by environment.
abr 18 07:20:20 pc-main gnome-shell[3251]: GNOME Shell started at Wed Apr 18 2018 07:20:12 GMT-0300
abr 18 07:20:18 pc-main gnome-shell[3251]: Some code accessed the property 'State' on the module 'docking'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but i
abr 18 07:20:17 pc-main org.gnome.Shell.desktop[3251]: Window manager warning: "XF86RFKill" is not a valid accelerator
abr 18 07:20:17 pc-main gnome-shell[3251]: Error looking up permission: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.impl.portal.PermissionStore was not provided by any .servic
abr 18 07:20:17 pc-main gnome-shell[3251]: Some code accessed the property 'dbusNodeImplementsInterfaces' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previou
abr 18 07:20:17 pc-main gnome-shell[3251]: Some code accessed the property 'introspectBusObject' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously suppo
abr 18 07:20:17 pc-main gnome-shell[3251]: [AppIndicatorSupport-WARN] Failed to acquire org.kde.StatusNotifierWatcher
abr 18 07:20:17 pc-main gnome-shell[3251]: Some code accessed the property 'Logger' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is 
abr 18 07:20:16 pc-main gnome-shell[3251]: WARNING: addSignalMethods is replacing existing [0x55dc11f87720 Gjs_ShowAppsIcon.dash-item-container] emit method
abr 18 07:20:16 pc-main gnome-shell[3251]: WARNING: addSignalMethods is replacing existing [0x55dc11f87720 Gjs_ShowAppsIcon.dash-item-container] disconnect method
abr 18 07:20:16 pc-main gnome-shell[3251]: WARNING: addSignalMethods is replacing existing [0x55dc11f87720 Gjs_ShowAppsIcon.dash-item-container] connect method
abr 18 07:20:16 pc-main gnome-shell[3251]: JS WARNING: [resource:///org/gnome/shell/ui/workspaceThumbnail.js 892]: reference to undefined property "_switchWorkspaceNotifyId"
abr 18 07:20:16 pc-main gnome-shell[3251]: WARNING: addSignalMethods is replacing existing [0x55dc111709c0 Gjs_ShowAppsIcon.dash-item-container] emit method
abr 18 07:20:16 pc-main gnome-shell[3251]: WARNING: addSignalMethods is replacing existing [0x55dc111709c0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
abr 18 07:20:16 pc-main gnome-shell[3251]: WARNING: addSignalMethods is replacing existing [0x55dc111709c0 Gjs_ShowAppsIcon.dash-item-container] connect method
abr 18 07:20:16 pc-main gnome-shell[3251]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/extension.js 44]: assignment to undeclared variable runningExtensions
abr 18 07:20:16 pc-main gnome-shell[3251]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1361]: unreachable code after return statement
abr 18 07:20:16 pc-main gnome-shell[3251]: Some code accessed the property 'traverseBusNames' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supporte
abr 18 07:20:16 pc-main gnome-shell[3251]: Some code accessed the property 'StatusNotifierWatcher' on the module 'interfaces'. That property was defined with 'let' or 'const' inside the module. This was previous
abr 18 07:20:16 pc-main gnome-shell[3251]: Some code accessed the property 'StatusNotifierWatcher' on the module 'statusNotifierWatcher'. That property was defined with 'let' or 'const' inside the module. This w
abr 18 07:20:16 pc-main gnome-shell[3251]: Some code accessed the property 'WORKAROUND_RELOAD_TYPE_REGISTER' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was prev
abr 18 07:20:16 pc-main gnome-shell[3251]: Some code accessed the property 'DBusMenu' on the module 'interfaces'. That property was defined with 'let' or 'const' inside the module. This was previously supported,
abr 18 07:20:12 pc-main gnome-shell[3251]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
abr 18 07:20:11 pc-main gnome-shell[3251]: Telepathy is not available, chat integration will be disabled.
abr 18 07:20:11 pc-main gnome-shell[3251]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
abr 18 07:20:10 pc-main gnome-shell[3251]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
abr 18 07:20:10 pc-main gnome-shell[3251]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"

**Comment by zagortenay333** [comment]
Well, I can't see anything there :disappointed: Are you on wayland maybe?

**Comment by unit-cesar** [comment]
I use XORG because it is required by Synergy (mouse shared). I will reboot and test without XORG.

**Comment by unit-cesar** [comment]
I tried, but I could not login without Xorg. Could not take the test!

**Comment by zagortenay333** [comment]
You're gonna have to tweak the code in order to debug this.

Change this:
https://github.com/zagortenay333/timepp__gnome/blob/c08e7feb9f4f3a5809ee46539669d121ec3596cc/lib/sound_player.js#L31-L42

..to this:
```js
    play: function (do_repeat = true) {
        try {
        if (this.playing || !this.sound_uri) return;

        if (do_repeat) {
            this.playbin.set_state(Gst.State.PLAYING);
            this.playing = true;
        }
        else {
            let [filename,] = GLib.filename_from_uri(this.sound_uri);
            global.play_sound_file(0, filename, '', null);
        }
        } catch (e) {
            log(">>>>>>>>>>>>>>>>>>>>>> TIMEPP: ");
            logError(e);
        }
    },
```
Restart the shell, and then play a notif on one repetition and look for errors again with the above commands.

**Comment by unit-cesar** [comment]
No log errors. So I added a few more logs, see the image and the output in the log:

abr 19 18:02:39 pc-main gnome-shell[3168]: Test... else {
abr 19 18:02:39 pc-main gnome-shell[3168]: Test...
abr 19 18:02:05 pc-main gnome-shell[3168]: GNOME Shell started at Thu Apr 19 2018 18:02:00 GMT-0300


![image](https://user-images.githubusercontent.com/11687314/39018632-fcfda56c-43fc-11e8-8cb9-7ddbb0ecf2dd.png)

**Comment by zagortenay333** [comment]
The code is triggered, so it must be something about that play_sound_file func. Try this:
```js
    play: function (do_repeat = true) {
        if (this.playing || !this.sound_uri) return;

        if (do_repeat) {
            this.playbin.set_state(Gst.State.PLAYING);
            this.playing = true;
        }
        else {
            let [filename,] = GLib.filename_from_uri(this.sound_uri);
            log(">>>>>>>>>>> TIMEPP: " + filename);
            global.play_sound_file(0, filename, '', null);
        }
    },
```

**Comment by unit-cesar** [comment]
abr 19 18:53:52 pc-main gnome-shell[3168]: >>>>>>>>>>> TIMEPP: /home/devesa/.local/share/gnome-shell/extensions/timepp@zagortenay333/data/sounds/bell.ogg

**Comment by zagortenay333** [comment]
Did you try other sound files besides bell.ogg?

**Comment by unit-cesar** [comment]
Yes, others of same folder and mp3 too.

**Comment by zagortenay333** [comment]
Do you have `libcanberra` and `libgsound0` installed?

**Comment by zagortenay333** [comment]
Try installing `gsound-tools` then.

**Comment by zagortenay333** [comment]
Actually, I'm not sure which package you need exactly. Maybe `libcanberra0`.

**Comment by unit-cesar** [comment]
I installed `gsound-tools` ... restart (Alt+F2 R)... but still nothing!

**Comment by zagortenay333** [comment]
As I said, I'm not sure which package you exactly need.

Here you can see what's installed on my system after executing `apt search libcanberra`:
```
gir1.2-gsound-1.0/artful 1.0.2-1ubuntu1 i386
  small library for playing system sounds (gir bindings)

gnome-session-canberra/artful,now 0.30-3ubuntu1 i386 [installed]
  GNOME session log in and log out sound events

gsound-tools/artful 1.0.2-1ubuntu1 i386
  small library for playing system sounds (tools)

libcanberra-dev/artful 0.30-3ubuntu1 i386
  simple abstract interface for playing event sounds

libcanberra-doc/artful 0.30-3ubuntu1 all
  simple abstract interface for playing event sounds - doc

libcanberra-gstreamer/artful 0.30-3ubuntu1 i386
  GStreamer backend for libcanberra

libcanberra-gtk-common-dev/artful 0.30-3ubuntu1 all
  simple abstract interface for playing event sounds

libcanberra-gtk-dev/artful 0.30-3ubuntu1 i386
  simple abstract interface for playing event sounds

libcanberra-gtk-module/artful,now 0.30-3ubuntu1 i386 [installed]
  translates GTK+ widgets signals to event sounds

libcanberra-gtk0/artful,now 0.30-3ubuntu1 i386 [installed]
  GTK+ helper for playing widget event sounds with libcanberra

libcanberra-gtk3-0/artful,now 0.30-3ubuntu1 i386 [installed]
  GTK+ 3.0 helper for playing widget event sounds with libcanberra

libcanberra-gtk3-dev/artful 0.30-3ubuntu1 i386
  simple abstract interface for playing event sounds

libcanberra-gtk3-module/artful,now 0.30-3ubuntu1 i386 [installed]
  translates GTK3 widgets signals to event sounds

libcanberra-pulse/artful,now 0.30-3ubuntu1 i386 [installed]
  PulseAudio backend for libcanberra

libcanberra0/artful,now 0.30-3ubuntu1 i386 [installed]
  simple abstract interface for playing event sounds

libgsound-dev/artful 1.0.2-1ubuntu1 i386
  small library for playing system sounds (devel)

libgsound-doc/artful 1.0.2-1ubuntu1 all
  small library for playing system sounds (documentation)

libgsound0/artful,now 1.0.2-1ubuntu1 i386 [installed,automatic]
  small library for playing system sounds
```

**Comment by zagortenay333** [comment]
Btw, I don't think you can use `whereis` to check for presence of these lib files.

**Comment by unit-cesar** [comment]
`apt search libcanberra`

```
Sorting... Pronto
Full Text Search... Pronto
gir1.2-gsound-1.0/artful 1.0.2-1ubuntu1 amd64
  small library for playing system sounds (gir bindings)

gnome-session-canberra/artful,now 0.30-3ubuntu1 amd64 [installed]
  GNOME session log in and log out sound events

gsound-tools/artful,now 1.0.2-1ubuntu1 amd64 [installed]
  small library for playing system sounds (tools)

libcanberra-dev/artful 0.30-3ubuntu1 amd64
  simples interface abstrata para tocar eventos de som

libcanberra-doc/artful,artful 0.30-3ubuntu1 all
  simple abstract interface for playing event sounds - doc

libcanberra-gstreamer/artful 0.30-3ubuntu1 amd64
  GStreamer backend for libcanberra

libcanberra-gtk-common-dev/artful,artful 0.30-3ubuntu1 all
  simples interface abstrata para tocar eventos de som

libcanberra-gtk-dev/artful 0.30-3ubuntu1 amd64
  simples interface abstrata para tocar eventos de som

libcanberra-gtk-module/artful,now 0.30-3ubuntu1 amd64 [installed]
  translates GTK+ widgets signals to event sounds

libcanberra-gtk0/artful,now 0.30-3ubuntu1 amd64 [installed]
  GTK+ helper for playing widget event sounds with libcanberra

libcanberra-gtk3-0/artful,now 0.30-3ubuntu1 amd64 [installed]
  GTK+ 3.0 helper for playing widget event sounds with libcanberra

libcanberra-gtk3-dev/artful 0.30-3ubuntu1 amd64
  simples interface abstrata para tocar eventos de som

libcanberra-gtk3-module/artful,now 0.30-3ubuntu1 amd64 [installed]
  translates GTK3 widgets signals to event sounds

libcanberra-pulse/artful,now 0.30-3ubuntu1 amd64 [installed,automatic]
  PulseAudio backend for libcanberra

libcanberra0/artful,now 0.30-3ubuntu1 amd64 [installed]
  simples interface abstrata para tocar eventos de som

libgsound-dev/artful 1.0.2-1ubuntu1 amd64
  small library for playing system sounds (devel)

libgsound-doc/artful,artful 1.0.2-1ubuntu1 all
  small library for playing system sounds (documentation)

libgsound0/artful,now 1.0.2-1ubuntu1 amd64 [installed,automatic]
  small library for playing system sounds

```

**Comment by zagortenay333** [comment]
Well, I'm out of ideas then. I don't know why that function doesn't work on your machine..

**Comment by tnilzon** [comment]
Can confirm: Sound does not work at all (not even with repeat set). Also checked dependencies.
System is Manjaro Gnome 18.0 with Gnome 3.30.2

**Comment by zagortenay333** [comment]
I realized after installing gnome-shell on xubuntu that I needed to install gstreamer. So I installed this:

> sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools

Can you try installing the above, @tnilzon ?

**Comment by tnilzon** [comment]
I am on Manjaro (Arch) so packages are not the same as in Debian. Really can't say anything about that you have listed, but my system is gnome (and includes gstreamer). Also, other sound events in my system works. This extension really should not be needing any other dependencies on a gnome (3.30.2) system?

**Comment by v-marinkov** [comment]
> I realized after installing gnome-shell on xubuntu that I needed to install gstreamer. So I installed this:
> 
> > sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools
> 
> Can you try installing the above, @tnilzon ?.

I just tried on Pop!_Os 18.04 (ubuntu based) with Gnome 3.28.3 and restarted Gnome shell, but still no sound.

**Comment by zagortenay333** [comment]
@tnilzon et. al, could you try running this extension: https://github.com/felipeborges/gnome-shell-extension-focusli and see whether the sound plays?

**Comment by tnilzon** [comment]
**@zagortenay333** OK I have tried the 'Focusli' extension. And, yes this extension plays sounds.

**Comment by v-marinkov** [comment]
@zagortenay333 I also confirm it plays correctly

**Comment by zagortenay333** [comment]
Just as a sanity check, did you guys turn on sound in the gtk settings?

**Comment by v-marinkov** [comment]
@zagortenay333 If you mean the settings of the extension, then yes.

**Comment by zagortenay333** [comment]
@v-marinkov can you check whether you have any errors with:
`journalctl /usr/bin/gnome-shell -f`

**Comment by v-marinkov** [comment]
Just this `Ignoring excess values in shadow definition`

**Comment by Beutlin** [comment]
@tnilzon
I've the same problem and could solve it.
Open  Gnome Control Center and go to the sound section. Here is a tab "sound effect".
The alert volume must be active. That means if you click on "bark" your loudspeaker must play a tone.

**Comment by zagortenay333** [comment]
@Beutlin Hah, it seems that really is it!

**Comment by zagortenay333** [comment]
@CesarDevesa @v-marinkov Could you check this?

**Comment by unit-cesar** [comment]
I think I can not contribute much, for security I have only used packages coming from the official repository (https://extensions.gnome.org/extension/1238/time/). What I can say is that some things do not work, like the Pomodoro icon that does not appear in the status bar and the alarm audio does not work in any configuration.

**Comment by zagortenay333** [comment]
@CesarDevesa The pomodor thing is fixed in github version.

Did you check the comment given by @Beutlin above?

**Comment by unit-cesar** [comment]
Yes, I did the test again and the audio only plays once, if I check "Repeat notifications sound" it does not play anymore. Which is not a big problem. Because I can put an audio of about 2 minutes and ok. But the Pomodoro icon does not appear in the status bar!

I have a suggestion for Pomodoro. That it can be defined in fixed time, when setting the start and end time of the work, be configured in a way that every day Short Breaks and Long Breaks happen at the same time.

**Comment by CesarDevesa** [comment]
I'm currently using a Chrome extension to configure this way.

![image](https://user-images.githubusercontent.com/11687314/50309220-d1926980-047c-11e9-8d0c-1666544fba6b.png)

**Comment by wfpaisa** [comment]
After reload the Shell works!, Alt + F2 -> r
